remote_write:
  - url: http://tasks.distributor:8080/api/v1/push
    headers:
      X-Scope-OrgID: 027400258944_a92761d7-c28b-4b6d-90e3-14abc1fbecb7
    write_relabel_configs:
      - source_labels: ['job']
        regex: 'cortex.*'
        action: drop


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: cortex/distributor
    scrape_interval: 15s
    dns_sd_configs:
      - names:
          - tasks.distributor
        type: A
        port: 8080

  - job_name: cortex/ingester
    scrape_interval: 15s
    dns_sd_configs:
      - names:
          - tasks.ingester
        type: A
        port: 8080